<?php

/**
 * Date 14/04/2023
 *
 * @author   Simon Siva <simonsiva13@gmail.com>
 */
return [
    'class' => '\Ssiva\MpesaYiiSdk\MpesaDaraja',
    'configs' => [
        'api_url' => "https://sandbox.safaricom.co.ke",
        'max_txn' => "125000",
        'min_txn' => "100",
        'apps' => [
            'default' => [
                'consumer_key' => "",
                'consumer_secret' => "",
            ],
            'branch' => [
                'consumer_key' => "",
                'consumer_secret' => "",
            ],
        ],
        'cache' => [
            'driver' => "",
            'file' => [
                'driver' => 'file',
                'path' => '',
            ],
            'redis' => [
                'driver' => 'redis',
                'connection' => 'default',
            ],
        ],
        /*
        |--------------------------------------------------------------------------
        | Account API Online Config
        |--------------------------------------------------------------------------
        |
        */
        'account' => [
            'short_code' => "",
            'result_url' => "",
            'timeout_url' => "",
            'initiator_name' => "",
            'security_credential' => "",
            'security_cert' => "",
            'identifier_type' => "",
            'balance' => [
                'default_command_id' => 'AccountBalance',
            ],
            'reversal' => [
                'default_command_id' => 'TransactionReversal',
            ],
            'transaction' => [
                'default_command_id' => 'TransactionStatusQuery',
            ],
        ],
        /*
        |--------------------------------------------------------------------------
        | LipaNaMpesa API Online Config
        |--------------------------------------------------------------------------
        |
        */
        'mpesa_online' => [
            /*
            |--------------------------------------------------------------------------
            | Paybill Number
            |--------------------------------------------------------------------------
            |
            | This is a registered Paybill Number that will be used as the Merchant ID
            | on every transaction. This is also the account to be debited.
            |
            |
            |
            */
            'short_code' => "",
            /*
            | STK Push callback URL
            |--------------------------------------------------------------------------
            |
            | This is a fully qualified endpoint queried by Safaricom's
            | API on completion or failure of a push transaction.
            |
            */
            'callback' => "",
            /*
            |--------------------------------------------------------------------------
            | SAG Passkey generated by Safaricom on registration of the Merchant's Paybill Number.
            |--------------------------------------------------------------------------
            */
            'passkey' => "",
            /*
            |--------------------------------------------------------------------------
            | Default Transaction Type set on every STK Push request
            |--------------------------------------------------------------------------
            */
            'default_transaction_type' => "",
        ],
        /*
        |--------------------------------------------------------------------------
        | B2C API Config
        |--------------------------------------------------------------------------
        |
        */
        'b2c' => [
            'short_code' => "",
            'result_url' => "",
            'timeout_url' => "",
            'initiator_name' => "",
            'security_credential' => "",
            'security_cert' => "",
            'identifier_type' => "",
            'default_command_id' => "",
        ],
        /*
        |--------------------------------------------------------------------------
        | B2B API Config
        |--------------------------------------------------------------------------
        |
        */
        'b2b' => [
            'short_code' => "",
            'result_url' => "",
            'timeout_url' => "",
            'initiator_name' => "",
            'security_credential' => "",
            'security_cert' => "",
            'identifier_type' => "",
            'default_command_id' => "",
            'sender_identifier' => "",
            'receiver_identifier' => "",
        ],
        /*
           |--------------------------------------------------------------------------
           | C2B API Config
           |--------------------------------------------------------------------------
           |
           */
        'c2b' => [
            'short_code' => "",
            'default_command_id' => "",
            'confirmation_url' => "",
            'validation_url' => "",
            'response_type' => "",
        ],
    ],
];
